### ISSUE TITLE
wrong data structure in training data

### ISSUE THREAD

**Issue by kristiank** [marfors/paradigmextract#1]
I get the following parse error when giving the training input:

```bash
paradigmextract]$ python src/pextract.py < ddninsharedtaskformat/es-verb-train > es_verb.p
Traceback (most recent call last):
  File "src/pextract.py", line 416, in <module>
    form, tag = l.split(u'\t')
ValueError: too many values to unpack
```

**Comment by marfors** [comment]
We need to clean up the repository (the data used in the example is actually not added to the repository, and the data you refer to uses a slightly different format).

But before then, here is a minimal example to illustrate the input format:

— english.txt
car case=nom,num=sg
cars case=nom,num=pl

bar case=nom,num=sg
bars case=nom,num=pl
—

$ python src/pextract.py < english.txt  > english.p

I.e., two fields, tab-separated. Tables are separated with a newline. The first form in a table is assumed to be the lemma (’car’ and ’bar’).

Best regards,
Markus

17 aug. 2017 kl. 18:24 skrev Kristian Kankainen <notifications@github.com<mailto:notifications@github.com>>:


I get the following parse error when giving the training input:

paradigmextract]$ python src/pextract.py < ddninsharedtaskformat/es-verb-train > es_verb.p
Traceback (most recent call last):
  File "src/pextract.py", line 416, in <module>
    form, tag = l.split(u'\t')
ValueError: too many values to unpack

**Comment by kristiank** [comment]
Thanks. The new format is better than the old one since the lemmas can collide and should thus not be used as identifiers.
