### ISSUE TITLE
Problems when using a very small dataset as input

### ISSUE THREAD

**Issue by kristiank** [marfors/paradigmextract#2]
Peculiar FSTs are compiled using a very small amount of input data (e.g this [pfile](https://github.com/keeleleek/dfdl-pextract-schema/blob/master/examples/vot_noun.p)). I cannot verify this behaviour with larger datasets since the input data in ``ddninsharedtaskformat`` and ``data/ddninsharedtaskformat`` are in the old wrong format.

Using the different options:
- -c defines an empty transducer
```
def Alph "m"|"g"|"p"|"j"|"k"|"d"|"e"|"_"|"ä"|"i"|"ü"|"ö"|"a"|"z"|"v"|"t"|"õ"|"o"|"s"|"l";
def p1=aikõ=var1 Alph+;
def p2=tüttö=var1 Alph+;
def p2=tüttö=var3 Alph+;
def p3=aapõ=var1 Alph+;
def p4=ammõz=var1 Alph+;
def p5=poikõ=var1 Alph+;
def Gconstrained ;
regex Gconstrained;
save stack analyzer.bin
```
- -u defines a transducer that doesn't use the Alph
```
def Alph "m"|"g"|"p"|"j"|"k"|"d"|"e"|"_"|"ä"|"i"|"ü"|"ö"|"a"|"z"|"v"|"t"|"õ"|"o"|"s"|"l";
def Gunconstrained p1=aikõ | p2=tüttö | p3=aapõ | p4=ammõz | p5=poikõ;
regex Gunconstrained;
save stack analyzer.bin
```
- -o defines a transducer that seems to be correct

**Comment by mhulden** [comment]
It seems some "optimizations" had slipped into the code. I've reverted to a previous version. The -c shouldn't give a different result than -u with so few examples, though. To see the difference, there needs to be more inflection tables collapsed into a single paradigm.
